### ISSUE TITLE
no directions shown when wego.here.com has empty origin

### ISSUE THREAD

**Issue by david-r-edgar** [david-r-edgar/MapSwitcher#1]
eg. found through this link:
https://wego.here.com/directions/mix//Wigtown-Scotlands-National-Book-Town,-South-Main-Street,-Wigtown:e-eyJuYW1lIjoiV2lndG93biAtIFNjb3RsYW5kJ3MgTmF0aW9uYWwgQm9vayBUb3duIiwiYWRkcmVzcyI6IlNvdXRoIE1haW4gU3RyZWV0LCBXaWd0b3duIiwibGF0aXR1ZGUiOjU0Ljg2ODE1NjgzMTIzLCJsb25naXR1ZGUiOi00LjQ0MjU4NDk0ODQ5NjUsInByb3ZpZGVyTmFtZSI6ImZhY2Vib29rIiwicHJvdmlkZXJJZCI6MTk1ODEwNTE3MTQ4NTYzfQ==?map=54.86816,-4.44258,17,normal&fb_locale=en_GB

sites with no directions are output correctly.

Console error logs of this form are shown for the popup:

extensions::uncaught_exception_handler:8 Error in response to storage.get: TypeError: Cannot use 'in' operator to search for 'address' in null
    at Object.generate (chrome-extension://mbeolgpgbnafkpoocbdanbibnbalblkg/src/outputMaps.js:55:31)
    at null.callback (chrome-extension://mbeolgpgbnafkpoocbdanbibnbalblkg/src/mapSwitcher.js:355:42)
    at chrome-extension://mbeolgpgbnafkpoocbdanbibnbalblkg/src/mapSwitcher.js:353:39
    at Object.run (chrome-extension://mbeolgpgbnafkpoocbdanbibnbalblkg/src/mapSwitcher.js:358:15)
    at Promise.all.then.then.then.then.s (chrome-extension://mbeolgpgbnafkpoocbdanbibnbalblkg/src/mapSwitcher.js:428:32)

**Comment by david-r-edgar** [comment]
Fixed at 48f7bd9b7489b195fafbdec52bae7bc9d8bbbf42
